/* Generated By:JJTree: Do not edit this line. ASTAndOrExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.util.Vector;	// PLB

public
class ASTAndOrExpr extends SimpleNode {
  public ASTAndOrExpr(int id) {
    super(id);
  }

  public ASTAndOrExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  //PLB
  private Vector ops = new Vector();
  public void addOp(String o) { ops.add(o); }
  public Vector getOps() { return ops; }
  
}
/* JavaCC - OriginalChecksum=36c5e8a5e4984bedcab4a29fdff82606 (do not edit this line) */
