/* Generated By:JJTree: Do not edit this line. ASTNotExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */


import java.util.Vector;	// PLB


public
class ASTNotExpr extends SimpleNode {
  public ASTNotExpr(int id) {
    super(id);
  }

  public ASTNotExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  //PLB
  private Vector ops = new Vector();
  public void addOp(String o) { ops.add(o); }
  public Vector getOps() { return ops; }
}
/* JavaCC - OriginalChecksum=6e1b0d64aea4020bdeb0d7101abcfde1 (do not edit this line) */
