/* Generated By:JJTree: Do not edit this line. ASTNegExpr.java */


import java.util.Vector;	// PLB

public class ASTNegExpr extends SimpleNode {
  public ASTNegExpr(int id) {
    super(id);
  }

  public ASTNegExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private Vector ops = new Vector();
  public void addOp(String o) { ops.add(o); }
  public Vector getOps() { return ops; }
}
