/* Generated By:JJTree: Do not edit this line. ASTPowExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.util.Vector;	// PLB

public
class ASTPowExpr extends SimpleNode {
  public ASTPowExpr(int id) {
    super(id);
  }

  public ASTPowExpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  //PLB
  private Vector ops = new Vector();
  public void addOp(String o) { ops.add(o); }
  public Vector getOps() { return ops; }
  
}
/* JavaCC - OriginalChecksum=149f75e94391cd3c0f4c3ca08a3ae349 (do not edit this line) */
