/* Generated By:JJTree: Do not edit this line. ASTAddExpr.java */

import java.util.Vector;	// PLB

public class ASTAddExpr extends SimpleNode {
  public ASTAddExpr(int id) {
    super(id);
  }

  public ASTAddExpr(LEParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LEParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private Vector ops = new Vector();
  public void addOp(String o) { ops.add(o); }
  public Vector getOps() { return ops; }
}
