/* Generated By:JJTree: Do not edit this line. ASTFctExpr.java */

public class ASTFctExpr extends SimpleNode {
  public ASTFctExpr(int id) {
    super(id);
  }

  public ASTFctExpr(LEParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LEParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private String value = null;
  public void setValue(String v) { value = v; }
  public String getValue() { return value; }
}
