/* Generated By:JJTree: Do not edit this line. ASTIOStmt.java */

public class ASTIOStmt extends SimpleNode {
  public ASTIOStmt(int id) {
    super(id);
  }

  public ASTIOStmt(LEParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LEParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  // PLB
  private String op = null;
  public void setOp(String o) { op = o; }
  public String getOp() { return op; }
}
